version: "2"
services:
  namenode:
    image: apache/hadoop:2.10.2
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9070:50070
      - 9470:50470
      - 9020:8020
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
  datanode:
    image: apache/hadoop:2.10.2
    command: ["hdfs", "datanode"]
    ports:
      - 9075:50075
      - 9475:50475
      - 9010:50010
    env_file:
      - ./config
  resourcemanager:
    image: apache/hadoop:2.10.2
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 9088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
  nodemanager:
    image: apache/hadoop:2.10.2
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config